package terraform

import (
	"fmt"
	"strings"
	"text/template"
	"bytes"

	"github.com/fathomforge/iam-assist/internal/policy"
)

// google_*_iam_member is non-authoritative and binds exactly ONE member per
// resource. Multiple members on the same role must therefore be emitted as
// multiple resource blocks. The templates below iterate (binding × member)
// to enforce this. All user-supplied strings are passed through `tfStr` for
// HCL escaping so that quote-bearing values (notably CEL expressions) cannot
// break out of their enclosing string literal.

const projectBindingTmpl = `# Generated by iam-assist — {{ tfStr .Request }}
# Risk: {{ .Risk.Level }}{{ range .Risk.Reasons }}
#   - {{ . }}{{ end }}
{{ range .Warnings }}
# ⚠️  {{ . }}
{{ end }}
{{- if .CustomRole }}
resource "google_project_iam_custom_role" "{{ .CustomRole.ID }}" {
  project     = "{{ tfStr .ProjectID }}"
  role_id     = "{{ tfStr .CustomRole.ID }}"
  title       = "{{ tfStr .CustomRole.Title }}"
  description = "{{ tfStr .CustomRole.Description }}"
  stage       = "{{ tfStr .CustomRole.Stage }}"
  permissions = [
    {{- range $i, $p := .CustomRole.Permissions }}
    "{{ tfStr $p }}",
    {{- end }}
  ]
}
{{ end }}
{{- range $bi, $b := .Bindings }}
{{- range $mi, $m := $b.Members }}
resource "google_project_iam_member" "{{ resourceName $b.Role $bi $mi }}" {
  project = "{{ tfStr $.ProjectID }}"
  role    = {{ roleRef $b.Role $.CustomRole }}
  member  = "{{ tfStr $m.IAMIdentity }}"
  {{- if $b.Condition }}

  condition {
    title       = "{{ tfStr $b.Condition.Title }}"
    description = "{{ tfStr $b.Condition.Description }}"
    expression  = "{{ tfStr $b.Condition.Expression }}"
  }
  {{- end }}
}
{{ end }}
{{- end }}`

const folderBindingTmpl = `# Generated by iam-assist — {{ tfStr .Request }}
{{- range $bi, $b := .Bindings }}
{{- range $mi, $m := $b.Members }}
resource "google_folder_iam_member" "{{ resourceName $b.Role $bi $mi }}" {
  folder = "folders/{{ tfStr $.FolderID }}"
  role   = "{{ tfStr $b.Role }}"
  member = "{{ tfStr $m.IAMIdentity }}"
  {{- if $b.Condition }}

  condition {
    title       = "{{ tfStr $b.Condition.Title }}"
    description = "{{ tfStr $b.Condition.Description }}"
    expression  = "{{ tfStr $b.Condition.Expression }}"
  }
  {{- end }}
}
{{ end }}
{{- end }}`

const orgBindingTmpl = `# Generated by iam-assist — {{ tfStr .Request }}
{{- range $bi, $b := .Bindings }}
{{- range $mi, $m := $b.Members }}
resource "google_organization_iam_member" "{{ resourceName $b.Role $bi $mi }}" {
  org_id = "{{ tfStr $.OrgID }}"
  role   = "{{ tfStr $b.Role }}"
  member = "{{ tfStr $m.IAMIdentity }}"
  {{- if $b.Condition }}

  condition {
    title       = "{{ tfStr $b.Condition.Title }}"
    description = "{{ tfStr $b.Condition.Description }}"
    expression  = "{{ tfStr $b.Condition.Expression }}"
  }
  {{- end }}
}
{{ end }}
{{- end }}`

// tfStringEscape escapes a string for safe inclusion inside an HCL double-
// quoted string literal. HCL's escape rules are a subset of Go's: backslash,
// double quote, and the usual control characters. Escaping ${ and %{ is also
// required to prevent unintended HCL template interpolation in user-supplied
// content (e.g. a CEL expression that legitimately contains "${var}").
func tfStringEscape(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
		`${`, `$${`,
		`%{`, `%%{`,
	)
	return r.Replace(s)
}

var funcMap = template.FuncMap{
	"tfStr": tfStringEscape,
	"resourceName": func(role string, bindingIdx, memberIdx int) string {
		// Convert "roles/bigquery.dataViewer" → "bigquery_data_viewer_0_0"
		// where the two indices are (binding index, member index) so every
		// emitted resource gets a unique Terraform address.
		name := role
		name = strings.TrimPrefix(name, "roles/")
		name = strings.TrimPrefix(name, "projects/")
		name = strings.ReplaceAll(name, ".", "_")
		name = strings.ReplaceAll(name, "/", "_")
		// Convert camelCase to snake_case before lowercasing.
		var result strings.Builder
		for i, r := range name {
			if r >= 'A' && r <= 'Z' {
				if i > 0 {
					result.WriteByte('_')
				}
				result.WriteRune(r + 32) // lowercase
			} else {
				result.WriteRune(r)
			}
		}
		return fmt.Sprintf("%s_%d_%d", result.String(), bindingIdx, memberIdx)
	},
	"roleRef": func(role string, customRole *policy.CustomRole) string {
		if customRole != nil && strings.Contains(role, customRole.ID) {
			return fmt.Sprintf("google_project_iam_custom_role.%s.id", customRole.ID)
		}
		return fmt.Sprintf(`"%s"`, tfStringEscape(role))
	},
}

// RenderData holds all data needed for template rendering.
type RenderData struct {
	Request    string
	Bindings   []policy.Binding
	Warnings   []string
	Risk       policy.RiskAssessment
	CustomRole *policy.CustomRole
	ProjectID  string
	FolderID   string
	OrgID      string
}

// Render produces Terraform HCL from a PolicyRecommendation.
func Render(rec *policy.PolicyRecommendation) (string, error) {
	risk := policy.Assess(rec)

	data := RenderData{
		Request:    rec.Request,
		Bindings:   rec.Bindings,
		Warnings:   rec.Warnings,
		Risk:       risk,
		CustomRole: rec.CustomRole,
	}

	var tmplStr string
	switch rec.Scope.Type {
	case "project":
		tmplStr = projectBindingTmpl
		data.ProjectID = rec.Scope.ID
	case "folder":
		tmplStr = folderBindingTmpl
		data.FolderID = rec.Scope.ID
	case "organization":
		tmplStr = orgBindingTmpl
		data.OrgID = rec.Scope.ID
	default:
		// Default to project-level.
		tmplStr = projectBindingTmpl
		data.ProjectID = rec.Scope.ID
	}

	tmpl, err := template.New("terraform").Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("rendering terraform: %w", err)
	}

	return buf.String(), nil
}
